version: "3"
services:
  app:
    container_name: express_server
    build: .
    ports:
      - "3001:3001"
    environment:
    - MONGO_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - express_app_db:/data/db
    ports:
      - "27017:27017"
    command: mongod
volumes:
  express_app_db:
  config: